import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import { Raleway } from "next/font/google";

const raleway = Raleway({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${raleway.className} antialiased bg-[#1A1A1F]`}>
        {children}
      </body>
    </html>
  );
}
